### ISSUE TITLE
attributes of entities dont save on mainQueueContext.save()

### ISSUE THREAD

**Issue by andertsk** [bignerdranch/CoreDataStack#111]
Hello, i writed the project using your CoreDataStack, and when i add some entities to DB and then save (mainQueueContext.save) only entities count is saved but not their attributes. Here is the project for see: [https://github.com/andertsk/PersonalContacts](url) (List tab)

**Comment by rcedwards** [comment]
This appears to be an issue in your application and outside of the scope of the CoreDataStack.

There are quite a few unit tests in place that ensure updating attribute values would be persisted.

It appears to me from scanning your code that the [`save()`](https://github.com/andertsk/PersonalContacts/blob/master/Enterprise%20contacts/WorkerTableViewController.swift#L285) function within `WorkerTableViewController` will not set property values when creating a new person and it will also not update the values of a person since it does not step into the following if `currentPersonType != initialPersonType`.

**Comment by andertsk** [comment]
Persons properties is set when form fields is changes. And then within save() function saveContext() is always called

**Comment by rcedwards** [comment]
@andertsk Step through with the debugger and you'll see where the issue lies.

**Comment by andertsk** [comment]
@rcedwards I can't bcause when i add person table is updated but after app restarted all entities have no props (have default props)
