### ISSUE TITLE
Creating CoreDataStack without dispatching

### ISSUE THREAD

**Issue by Aranoledur** [bignerdranch/CoreDataStack#157]
Hi everyone! I need a way to construct CoreDataStack SQLite type without dispatching. Is it possible right now?

**Comment by rcedwards** [comment]
Hi @Aranoledur nope thats not available by design.

Thanks https://github.com/bignerdranch/CoreDataStack/issues/31

**Comment by lyricsboy** [comment]
If you really do *need* to do it synchronously, you can use a semaphore (or something like XCTestExpectation in a unit test) to wait while the stack is being created, but as @rcedwards says, it's implemented this way because you generally don't want to block the main thread while CoreDataStack starts up.
