### ISSUE TITLE
When using Mogenerator, making a ManagedObject implement CoreDataModelable gives error

### ISSUE THREAD

**Issue by Yourney** [bignerdranch/CoreDataStack#158]
### Feature Request

_What would you like to see that is not available?_

I have created my Model Objects with MoGenerator.
When I make one of those generated classes implement CoreDataModelable, I get an error:
/Model/Custom/Region.swift:7:20: Getter for 'entityName' with Objective-C selector 'entityName' conflicts with method 'entityName()' from superclass '_Region' with the same Objective-C selector

### Question

Would it be a better idea to put all those very usefull functions in a straightforward:
extension NSManagedObject {
}

### Expected behavior

Either way, I would like to be able to use the useful functions you implemented in CoreDataModelable.

### Actual behavior

Compile error:
Getter for 'entityName' with Objective-C selector 'entityName' conflicts with method 'entityName()' from superclass '_Region' with the same Objective-C selector

### Additional Context

Xcode 7.3.1, Mogenerator 1.29, BNRCoreDataStack 1.2.5, Swift 2.2.

__Thanks for contributing to the CoreDataStack!__

**Comment by rcedwards** [comment]
Hi @Yourney 

This one is a bit tricky because MoGenerator is providing you with the `entityName()` function to provide some of the niceties and convenience methods we're also achieving by having `NSManagedObject` subclasses implement the `CoreDataModelable`.

Since our convenience methods depend on having a way of accessing your subclasses entity name there would be no way for us to move our functions directly to an extension on `NSManagedObject`.

Going forward if you're targeting iOS 10/macOS 10.12 and later `NSManagedObject`s get `entity` automatically via Xcodes subclass generation, so we'll be moving our functions into an extension then.

A solution for your case will have to be removing/renaming the conflicting name that is generated in the `_Base` class. Obviously not ideal though since this is supposed to be an auto generated file.

Thanks

**Comment by Yourney** [comment]
Hi Robert,

Thanks for your reply.
I see your point(s).

When using MoGenerator, I think one does not use 'Xcodes subclass generation'. Or do I misunderstand?
I think there must be a way to coexist ...
Changing the MoGenerator Template is not very desirable, but it should work.

Regards,
Wouter

**Comment by Yourney** [comment]
Wouldn't it solve this incompatibility if you'd make the protocol compatible with MoGenerator by making the var entityName a function?

Regards,
Wouter

**Comment by rcedwards** [comment]
Hi @Yourney that would possibility resolve the particular issue you're facing but that would be a breaking API change on our side.

Compatibility with MoGenerator is not a common request we've seen at this time and therefore something we're not current pursuing. Thanks

**Comment by Yourney** [comment]
I do not want to push or stalk or anything ... so if I am too persistent, please tell me ;-)
How does the typical BNRCoreDataStack user or use case produce the NSManagedObject subclasses? Perhaps there is an easier way for me to use that is compatible with BNRCoreDataStack?

I think that the Xcode built in subclassing mechanism is 'not automatic' and has no 'custom' subclass. Before I worked with MoGenerator, I used the Xcode function, and put my own stuff in a category. But MoGenerator gave me more flexibility.

Regards,
Wouter

**Comment by rcedwards** [comment]
@Yourney sure so in 2015 Apple introduced a template for generating NSManagedObject subclasses (still manually) that would place all the properties into an extension of your object so that you could freely edit your subclass and continually generate updates to your model that would replace the previous on disk. 
[Whats new in Core Data 2015](https://developer.apple.com/videos/play/wwdc2015/220/)

You can follow those steps and add `CoreDataModelable` conformance to your subclass.

In my experience I've typically shied away from automatically generating my subclasses for greater control. Especially since after you've established your initial model you're usually looking at minor changes.
