### ISSUE TITLE
Question: is `.findFirstInContext(...)` not available any more on iOS < 10?

### ISSUE THREAD

**Issue by haemi** [bignerdranch/CoreDataStack#188]
### Question

My app supports iOS versions >= 8.0 and I'd love to use CoreDataStack - unfortunately when I try to use `try MyCoreDataClass.findFirstInContext(context)`, I have to surround it with the iOS10-availability-stuff, which makes sense when looking into the source code.

But is there no way to use that with iOS 8 anymore?

**Comment by rcedwards** [comment]
Hi @haemi 

So there are now two definitions of `findFirstInContext()` since the introduction of `NSFetchRequestResult` in iOS 10.

[`NSFetchRequestResult` extension](https://github.com/bignerdranch/CoreDataStack/blob/master/Sources/NSManagedObject%2BFetchHelpers.swift#L44) will require the iOS 10.

If your `MyCoreDataClass` conforms to our [`CoreDataModelable` protocol](https://github.com/bignerdranch/CoreDataStack/blob/master/Sources/CoreDataModelable.swift#L17) you'll be able to use [`findFirstInContext()`](https://github.com/bignerdranch/CoreDataStack/blob/master/Sources/CoreDataModelable.swift#L85) on pre-iOS 10 targets.

More than likely your class is not conforming to `CoreDataModelable`:

```
class MyCoreDataClass: NSManagedObject {
    @NSManaged var myProperty: String?
}

extension MyCoreDataClass: CoreDataModelable {
    static var entityName: String {
        return "MyEntityName"
    }
}
``` 

Hope this helps.

**Comment by haemi** [comment]
ok, that really was the problem, thanks - is this documented somewhere? Some kind of Getting Started etc.?

**Comment by rcedwards** [comment]
[Deprecations](https://github.com/bignerdranch/coredatastack#deprecations) section of the README covers some of this along with some details in [NSManagedObject Extensions](https://github.com/bignerdranch/coredatastack#nsmanagedobject-extensions).

PRs are always welcome if you think it could be clearer. 😄 Thanks
