### ISSUE TITLE
Support programatically created object models

### ISSUE THREAD

**Issue by HSchultjan** [bignerdranch/CoreDataStack#189]
### Feature Request

As a developer i would like to construct a core data stack using an `NSManangedObjectModel` that was created programatically.

### Expected behavior

It should not matter how you define your object model for the CoreData stack.

### Actual behavior

You can't use an object model created in code. Neither can you subclass the `CoreDataStack` class, nor can you access the initializers to add said functionality.

**Comment by rcedwards** [comment]
Hi @HSchultjan thanks for your request.

The CoreDataStack was designed to be a thin abstraction layer a top CoreData's existing set of classes that alleviates the pain of constructing your stack. As such, the CoreDataStack aims to follow the [80/20 rule](http://wiki.c2.com/?EightyTwentyRule) in order to serve the most use cases without creating bloat and awkward usage API. I suspect that adding the ability to create a CoreDataStack with a pre-constructed model would begin to make the API more clumsy and serve only a small percentage of use cases.

With regards to sub-classing (CoreDataStack being final) and private initializers, this is intentional to better serve the simplicity of the API as described above.

For use-cases outside of the 80/20 rule I'd suggest using the CoreData classes directly, as this would compose a more usable API for the specific use case. I also suggest using `NSPersistentContainer` if targeting iOS 10 is an available option.

Thanks

**Comment by rcedwards** [comment]
Added in v2.2.0
