### ISSUE TITLE
Create stack synchronously

### ISSUE THREAD

**Issue by bitomule** [bignerdranch/CoreDataStack#31]
Is it possible to create the stack synchronously? I create it in app delegate and need to use it before any controller is created. Is it possible?

**Comment by rcedwards** [comment]
@bitomule It is not possible to create a SQLite backed CoreDataStack instance synchronously and this is by design. With SQLite backed stores it can take an indefinite amount of time to map your xcdatamodel into SQLite tables/rows, especially on first time launches or between model migrations.

Its is always a good practice to architect your app with the assumption that this could take a longer amount of time than you'd want to block the main thread.

In your case I would suggest doing one of two things:

1. You can make the CoreDataStack dependency on your view controllers an optional that is set once the setup has called back to you. In this scenario you need to ensure you'r view controller has something to display while the CoreDataStack is absent.

2. You can suspend setting up these initial view controllers within the AppDelegate until the stack has been created. A splash screen/spinner type of UI can be used here while the stack is being constructed.

**Comment by bitomule** [comment]
Thanks, I'll try showing a loading screen while creating stack.
