### ISSUE TITLE
Merge changes from newBatchOperationContext

### ISSUE THREAD

**Issue by bitomule** [bignerdranch/CoreDataStack#34]
I'm using a batchOperationContext to import a big data set. It works but I don't know why objects from one entity are saved on disk but not on memory. I'm trying to re-fetch from disk but can't make it work. 

Right now the only thing that works is creating a new batchOperationContext and fetching the entity there but this seems to be overkill.

Any ideas? How are changes from batchOperationContext merged into main context? Any way to reset main context and re-fetch from disk?

**Comment by rcedwards** [comment]
Changes that occur in a` batchOperationContext` are not ever merged into the main context by the `CoreDataStack`. This is also intentional. You can read more about this in our blog post introducing the stack: [Introducing the Big Nerd Ranch Core Data Stack](https://www.bignerdranch.com/blog/introducing-the-big-nerd-ranch-core-data-stack/) Here is the relevant excerpt regarding this.

> The changes could be propagated across contexts using the same pattern described in shared persistent store coordinator pattern using mergeChangesFromContextDidSaveNotification(). However, since this pattern is built for performance, it’s preferable to simply listen for the NSManagedObjectContextDidSaveNotification and re-perform your fetch request on the main queue context stack. This will be considerably faster than trying to merge thousands of objects between the two stacks.

You can see an example of inserting objects in a `batchOperationContext` and then refetching them in our unit tests. [BatchOperationContextTests](https://github.com/bignerdranch/CoreDataStack/blob/master/CoreDataStackTests/BatchOperationContextTests.swift#L54)

**Comment by bitomule** [comment]
Thanks for the quick reply @rcedwards , my issue was that I was downloading some data on main queue and after that some big import with duplicated data. That data already in memory didn't refresh from disk. Removed data duplication and not works as expected. Again, thanks.
