### ISSUE TITLE
Crash saving background context

### ISSUE THREAD

**Issue by bitomule** [bignerdranch/CoreDataStack#48]
Any idea on where's the issue in this crash?

````
Thread : Crashed: NSManagedObjectContext 0x15462eaa0: Background Worker Context
0  libswiftCore.dylib             4317556504 usesNativeSwiftReferenceCounting_unowned(void const*) + 156
1  libswiftCore.dylib             4317557536 swift_unknownWeakRelease + 36
2  BNRCoreDataStack               4305106224 _TFFE16BNRCoreDataStackCSo22NSManagedObjectContext11saveContextFS0_FTGSqFOS_13SuccessResultT___T_U_FGSqFS1_T__T_ + 268
3  CoreData                       6501320960 developerSubmittedBlockToNSManagedObjectContextPerform + 196
4  libdispatch.dylib              6860510888 _dispatch_client_callout + 16
5  libdispatch.dylib              6860560108 _dispatch_queue_drain + 864
6  libdispatch.dylib              6860525996 _dispatch_queue_invoke + 464
7  libdispatch.dylib              6860510888 _dispatch_client_callout + 16
8  libdispatch.dylib              6860569408 _dispatch_root_queue_drain + 2140
9  libdispatch.dylib              6860567260 _dispatch_worker_thread3 + 112
````

I can't find what called save context. It's a fabric remote crash report.

**Comment by lyricsboy** [comment]
Can you tell us which version of this library you're using?

Because we're using an `unowned` reference to `self` in the `saveContext` method, and that method executes asynchronously, it's possible for the `NSManagedObjectContext` instance to be deallocated by ARC before the async save block executes. If you're doing background work on another thread/queue that calls `saveContext` and finishes its work before that block is done, this could result.

While we could use `weak` and prevent the crash, it may make the code in `saveContext` a no-op, which is probably not what you would expect.

We'll look at making the memory semantics of this more clear, but the better fix is probably to use `saveContextAndWait` for background operations in your code instead.

**Comment by jeremy-w** [comment]
It might be more in keeping with the intent of a `save` call to drop both `unowned` and `weak` and instead hold a strong reference to the object till the save completes. I think this would take only a two-word change: remove the `[unowned self]` in `saveContext` from [SaveHelpers.swift:51](https://github.com/bignerdranch/CoreDataStack/blob/992a3e5ac585b4780109fae4ec7da2212a782fb6/CoreDataStack/NSManagedObjectContext%2BSaveHelpers.swift#L51).

**Comment by rcedwards** [comment]
@jeremy-w I like this idea. :+1:  I'll let @lyricsboy take a look today and see if we can put a unit test together to cover this case before proceeding.

**Comment by bitomule** [comment]
Can I help with it?

**Comment by jeremy-w** [comment]
@bitomule: Sure, the unowned -> strong switch outlined above will hopefully fix it. If you could apply that and verify that it stops your app from crashing, that would be awesome. :dancer: 

BTW, did the crash happen reliably for you, or was it only sometimes crashing?

I think @rcedwards was hoping to put a test over it, but that will be hard without introducing something like "build test-only project, run the executable from the test, wait for it to exit, fail if it didn't exit cleanly", since a failing test *within* the test process will kill the test process itself and prevent running other tests. :)

**Comment by bitomule** [comment]
@jeremy-w that could fix it but my issue only happened once after a lot's of saves so not easy way to test it.

**Comment by rcedwards** [comment]
Addressed in https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.0.2

**Comment by bitomule** [comment]
Thanks, will report if it occurs again. Btw, today we released our iOS app with a powerful core data stack :+1:

**Comment by rcedwards** [comment]
@bitomule fantastic news :tada: We're happy our stack was able to help with your project.
