### ISSUE TITLE
Wrong model name results in EXC_BAD_INSTRUCTION during constructSQLiteStack

### ISSUE THREAD

**Issue by eviltofu** [bignerdranch/CoreDataStack#74]
Can constructSQLiteStack return an error / errorType in the CoreDataStackSetupCallback when the model file does not exist?

**Comment by randomstep** [comment]
Taking a look at the implementation, I agree this could use some improvements. The bundle extension probably ought to just pass through nil rather than using IUOs.  Then the main initializer could guard on the model instantiation, and as you say it could return an error if the model or the store URL fails. 

Though constructing with an invalid model name seems initially to me like a programmer error rather than an expected or "normal" error.

**Comment by rcedwards** [comment]
Yes this should have been a `preconditionFailure` rather than a force unwrap so that you have a proper message in the console output.

Since this type of error is programmer error rather than a recoverable error, I would prefer not to `throw`.

**Comment by rcedwards** [comment]
Included in https://github.com/bignerdranch/CoreDataStack/releases/tag/v1.1.2
